## Encode a categorical variable using ML model

In [1]:
#Import required packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
#Read the data
dataset = pd.read_excel('/Users/swaruptripathy/Desktop/Data Science and AI/datasets/stark_data.xlsx')

In [5]:
dataset.head()

Character   Age  Gender  Survived
0    Eddard  52.0    Male         0
1      John  27.0    Male         1
2      Arya  21.0  Female         1
3      Bran  19.0    Male         1
4      Robb   NaN    Male         0

In [6]:
dataset.shape

(6, 4)

In [7]:
X = dataset.iloc[:,:-1].values
X

array([['Eddard', 52.0, 'Male'],
       ['John', 27.0, 'Male'],
       ['Arya', 21.0, 'Female'],
       ['Bran', 19.0, 'Male'],
       ['Robb', nan, 'Male'],
       ['Sansa', 24.0, 'Female']], dtype=object)

In [8]:
#Impute missing value using sklearn imputer from preprocessing
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer.fit(X[:, 1:2])
X[:, 1:2] = imputer.transform(X[:, 1:2])
X[:, 1:2]

/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[52.0],
       [27.0],
       [21.0],
       [19.0],
       [28.6],
       [24.0]], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
#column gender encoding
X[:,2] = labelencoder_X.fit_transform(X[:,2])
X[:,2]

array([1, 1, 0, 1, 1, 0], dtype=object)

In [10]:
#column name encoding
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([2, 3, 0, 1, 4, 5], dtype=object)

In [11]:
X

array([[2, 52.0, 1],
       [3, 27.0, 1],
       [0, 21.0, 0],
       [1, 19.0, 1],
       [4, 28.6, 1],
       [5, 24.0, 0]], dtype=object)

In [12]:
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
X

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[ 0. ,  0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])

In [14]:
X[:,1:] #Dropping the dummy variable

array([[ 0. ,  1. ,  0. ,  0. ,  0. , 52. ,  1. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. , 27. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. , 21. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. , 19. ,  1. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. , 28.6,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. , 24. ,  0. ]])