## NumPy Operations

In [1]:
#importing Numpy
import numpy as np

In [2]:
#Creating a List
myList = [1,2,3]
print(myList)
type(myList)

[1, 2, 3]


list

In [3]:
#Convert List to array
arr = np.array(myList)
print(arr)
type(arr)

[1 2 3]


numpy.ndarray

In [4]:
#Multiplying a list by 2
list_mul = myList * 2
list_mul

[1, 2, 3, 1, 2, 3]

In [5]:
#Multiplying an array by 2
arr_mul = arr * 2
arr_mul

array([2, 4, 6])

In [6]:
# String array
arr_char = np.array(['a','b','c'])

In [7]:
# Multiplying alpha characters
np.char.multiply(arr_char, 2)

array(['aa', 'bb', 'cc'], dtype='<U2')

In [8]:
arr

array([1, 2, 3])

In [9]:
#No of dimensions
arr.ndim

1

In [10]:
myTuple = (1,2,3)
print(myTuple)
type(myTuple)

(1, 2, 3)


tuple

In [11]:
arr_tuple = np.array(myTuple)
print(arr_tuple)
type(arr_tuple)

[1 2 3]


numpy.ndarray

In [12]:
#Tuple of array dimension
data = [(1,2,3),(4,5,6)]
arr2 = np.array(data)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.ndim

2

In [14]:
#List of array dimension
data = [[1,2,3],[4,5,6]]
new_arr = np.array(data)
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
new_arr.ndim

2

In [16]:
#Memory space consumed by the variable in bytes
new_arr.itemsize

4

In [17]:
#No of elements
new_arr.size

6

In [18]:
#Shape - To see no. of rows and columns
new_arr.shape

(2, 3)

In [19]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#Reshaping arrays
new_arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#Return a new array with the specified shape
np.resize(new_arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [22]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#Transpose an array
new_arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.transpose(new_arr)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
arr

array([1, 2, 3])

In [27]:
#Accessing array values
arr[1]

2

In [28]:
#           0  1  2  3  4
# arr_n = (([4, 5, 3, 7, 1]))
#          -5 -4 -3 -2 -1

arr_n = np.array([4,5,3,7,1])
arr_n

array([4, 5, 3, 7, 1])

In [29]:
arr_n[2]

3

In [30]:
arr_n[-3]

3

In [31]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
new_arr[1,2]

6

In [33]:
#Iterate index values
new_arr[0:,2]

array([3, 6])

In [34]:
n_arr = np.array([(1,2),(3,4),(5,6),(7,8)])
print(n_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
n_arr[0:,1]

array([2, 4, 6, 8])

In [36]:
n_arr[0:2,1] #i:i+1

array([2, 4])

In [37]:
n_arr[1]

array([3, 4])

In [38]:
n_arr[1:2]

array([[3, 4]])

In [39]:
n_arr[1:3]

array([[3, 4],
       [5, 6]])

In [40]:
n_arr = np.array([[(1,2),(3,4),(5,6),(7,8)]])
print(n_arr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [41]:
n_arr.ndim

3

In [42]:
# Fetching evenly spaced numbers over a specified interval
e_val = np.linspace(1,3,20)
e_val

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [43]:
# Fetch min value
print(arr)
arr.min()

[1 2 3]


1

In [44]:
# Fetch max value
arr.max()

3

In [45]:
# Sum of values in an array
print(arr)
arr.sum()

[1 2 3]


6

In [46]:
print(new_arr)
print("Sum of all the values: ",new_arr.sum())
print("Sum of along column: ",new_arr.sum(axis=0))
print("Sum of along row: ",new_arr.sum(axis=1))

[[1 2 3]
 [4 5 6]]
Sum of all the values:  21
Sum of along column:  [5 7 9]
Sum of along row:  [ 6 15]


In [47]:
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
#To get the square of all the values
new_arr**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [49]:
#Getting the square root of all the values
np.sqrt(new_arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
#Addition of multiple array elements
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(4,5,6)])
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
#Substraction of multiple array elements
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
#Multiplication of multiple array elements
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [53]:
#Division of multiple array elements
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
#Stack arrays - Vertical Stacking
arr1 = np.array([(1,2,3),(4,5,6)])
arr2 = np.array([(1,2,3),(4,5,6)])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
#Horizontal Stacking
np.hstack((arr1,arr2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
#Create sequence of numbers
np.arange(10,40,4)

array([10, 14, 18, 22, 26, 30, 34, 38])

In [57]:
#Generate an array of 1 elements
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
#Generate an array of 0 elements
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
#Changing the datatype of elements within an array
np.ones(10).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [60]:
#Creating an empty array
np.empty(5)

array([1.11260738e-307, 2.33646845e-307, 3.22649121e-307, 6.89799379e-307,
       3.22646744e-307])

In [61]:
#Creating an empty array
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
#Creating an array wih random numbers
np.random.rand(2,3) #2X3

array([[0.89191887, 0.4771327 , 0.67041927],
       [0.07991101, 0.50042653, 0.46028088]])