In [2]:
#Importing Numpy package
import numpy as np

In [3]:
#Check if a value is scalar
np.isscalar(23)

True

In [4]:
np.isscalar(False) # Boolean value is also scalar

True

In [5]:
np.isscalar([23]) # as it is a list it is not considered as scalar value

False

In [6]:
np.isscalar(45.6)

True

In [9]:
# Scalar Computations
s1 = 6
s2 = 4

print(s1+s2)
print(s1-s2)
print(s1*s2)
print(s1/s2)
print(s1//s2)

10
2
24
1.5
1


In [13]:
#Vectors
a = [1,2,3]
a * 2

[1, 2, 3, 1, 2, 3]

In [15]:
#Multiplying scalar to a vector
np.multiply(a,2)

array([2, 4, 6])

In [16]:
np.array(a) * 2

array([2, 4, 6])

In [14]:
#Adding scalar to a vector
np.add(a,2)

array([3, 4, 5])

In [17]:
#Multiple vectors
a = [10,15,18]
b = [11,23,42]
a + b

[10, 15, 18, 11, 23, 42]

In [18]:
#Vector Addition
np.add(a,b)

array([21, 38, 60])

In [20]:
#Vector Subtraction
np.subtract(a,b)

array([ -1,  -8, -24])

In [21]:
#Vector Addition
a = np.array([10,15,18])
b = np.array([11,23,42])
a + b

array([21, 38, 60])

In [24]:
#Multiply a scalar with a vector
np.multiply(a,3)

array([30, 45, 54])

In [22]:
# Dot product of two vectors
np.dot(a,b)

1211

In [23]:
# Cross product of two vectors
np.cross(a,b)

array([ 216, -222,   65])

In [29]:
#Finding out the magnitude of a vector
np.linalg.norm(a)

25.475478405713993